name: Terraform CI

# Trigger CI when a Pull Request targets the main branch
on:
  pull_request:
    branches:
      - main

# Permissions required by the workflow
permissions:
  # Allows GitHub Actions to request an OIDC token
  # This token is used to authenticate to AWS
  id-token: write

  # Allows the workflow to read the repository contents
  contents: read

jobs:
  terraform-check:

    # Run this job on a temporary Ubuntu machine provided by GitHub
    runs-on: ubuntu-latest

    steps:

      # Step 1:
      # Download/checkout the repository files onto the Ubuntu runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2:
      # Install/setup Terraform on the Ubuntu runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 3:
      # Authenticate GitHub Actions to AWS using OIDC
      # GitHub assumes the IAM role we created in AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::470880515561:role/GitHubTerraformRole
          aws-region: eu-west-2

      # Step 4:
      # Initialize the Terraform working directory
      # This also downloads the required AWS provider
      - name: Terraform Init
        run: terraform init

      # Step 5:
      # Check whether the Terraform configuration is valid
      - name: Terraform Validate
        run: terraform validate

      # Step: Scan Terraform code for security and compliance issues
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform

      # Step 6:
      # Check whether the Terraform files follow standard formatting
      # -check only checks formatting; it does not modify the files
      - name: Terraform Format Check
        run: terraform fmt -check

      # Step 7:
      # Show what Terraform plans to create, change, or destroy
      # This does not actually create any AWS resources
      - name: Terraform Plan
        run: terraform plan